name: Build

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: |
          ZIP=$(ls *.zip | head -n1)
          unzip -o "$ZIP" -d .

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build
        run: mvn -B clean package

      - name: Get jar
        uses: actions/upload-artifact@v4
        with:
          name: SparkPractice
          path: target/*.jar
